name: .NET Release Project

on:
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      shell: bash
      run: |
        tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        release_name="MazeRunner.Console-$tag-${{ matrix.target }}"
        
        if [ "${{ matrix.target }}" == "win-x64" ]; then
          csproj="${{ github.workspace }}\MazeRunner.Console\MazeRunner.Console.csproj"
        else
          csproj="${{ github.workspace }}/MazeRunner.Console/MazeRunner.Console.csproj"
        fi
        
        # Build everything
        dotnet publish "$csproj" --runtime "${{ matrix.target }}" -c Release --self-contained true -p:PublishTrimmed=true -p:DebugType=None -p:DebugSymbols=false -o "$release_name"
        
        # Move and rename the executable to a release folder
        mkdir release
        
        # Set environment variable from the release name
        echo "release_name=$release_name" >> $GITHUB_ENV
        
        if [ "${{ matrix.target }}" == "win-x64" ]; then
          mv "./$release_name/MazeRunner.Console.exe" "./release/$release_name.exe"
        else
          mv "./$release_name/MazeRunner.Console" "./release/$release_name"
        fi

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/MazeRunner*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        draft: true